# File to fetch current resort conditions HTML and parse via beautiful soup
from bs4 import BeautifulSoup
from requests_html import HTMLSession

import re
import requests

# Initializing Mountain Constants
COPPER = 'Copper'
ELDORA = 'Eldora'
STEAMBOAT = 'Steamboat'
WINTER_PARK = 'Winter Park'

# Initializing Resort Name to URL mapping
resort_to_url = {
    COPPER: "https://www.coppercolorado.com/the-mountain/conditions-weather/snow-report",
    ELDORA: "https://www.eldora.com/the-mountain/conditions-weather/current-conditions-forecast",
    #ELDORA: "https://www.eldora.com/the-mountain/conditions-weather/current-conditions-forecast?utm_source=Google&utm_medium=Cross-Device-Text&utm_campaign=DLA-Eldora-2021-POWDR-Eldora-Winter&utm_term=Search-Audience-Keywords-NA-Priority-Markets&utm_content=Multi&gclid=CjwKCAiAwKyNBhBfEiwA_mrUMoPu-j8ZjkHsFlTHMJmO94hZEZijWfbk3IwAPTY3oBm27sApQNFS4xoCqIQQAvD_BwE&gclsrc=aw.ds",
    STEAMBOAT: "https://www.steamboat.com/the-mountain/mountain-report#/",
    WINTER_PARK: "https://www.winterparkresort.com/the-mountain/mountain-report#/"
}


# In order to expand elements generated by Javascript, we need to use a special library
# https://stackoverflow.com/questions/8049520/web-scraping-javascript-page-with-python
def render_javascript_source_code(url_name):
    session = HTMLSession()
    r = session.get(url_name)
    r.html.render(sleep=2, timeout=20)

    return r.html.html


# Fetch the current conditions for the given resort name, returns JSON format
def scrape_resort_conditions_page(resort_name):
    conditions_url = resort_to_url[resort_name]
    resort_not_found_response = {"ERROR resort not found"}

    if resort_name == COPPER:
        raw_html = render_javascript_source_code(conditions_url)
        return read_copper_conditions(raw_html)
    elif resort_name == ELDORA:
        raw_html = render_javascript_source_code(conditions_url)
        return read_eldora_conditions(raw_html)
    elif resort_name == STEAMBOAT:
        raw_html = render_javascript_source_code(conditions_url)
        return read_steamboat_conditions(raw_html)
    elif resort_name == WINTER_PARK:
        response = requests.get(conditions_url)
        raw_html = response.text
        return read_winter_park_conditions(raw_html)
    else:
        return resort_not_found_response


# Debugging function to return pretty HTML version of a webpage
def parse_raw_html_for_conditions(raw_hmtl):
    conditions_soup = BeautifulSoup(raw_hmtl, 'html.parser')
    pretty_soup = conditions_soup.prettify()
    return pretty_soup


# Format the current weather conditions to a standard JSON style
def format_conditions_json(new_snow_inches, wind_speed, lifts_open, trails_open):
    conditions_json = {
        'NewSnowInches': new_snow_inches,
        'WindSpeed': wind_speed,
        'LiftsOpen': lifts_open,
        'TrailsOpen': trails_open
    }
    return conditions_json


# Read HTML file for conditions form Winter Park
def read_winter_park_conditions(raw_html):
    conditions_soup = BeautifulSoup(raw_html, 'html.parser')

    wind_speed = "-1"
    imperial_stats = conditions_soup.find_all('div', class_="switchable-stat-item switchable-stat-imperial")
    for tag in imperial_stats:
        tag_label = tag.find('span', class_="label")
        if tag_label:
            tag_label_text = tag_label.get_text()
            if tag_label_text == "Wind Speed":
                wind_speed = tag.find('span', class_='value').get_text()
                continue
        else:
            continue

    expected_snowfall_list_item = conditions_soup.find_all('li', class_="weather-forecast-snowfall-list-item")[0]
    new_snow_inches = expected_snowfall_list_item.find('div', class_="switchable-stat-item switchable-stat-imperial")\
        .find('span', class_="value")\
        .get_text()

    # list tag for open lifts and trails
    trail_conditions_tags = conditions_soup.find_all('li', class_="conditions-trails-content-others-metric")

    lifts_open = -1
    trails_open = -1
    for tag in trail_conditions_tags:
        metric_name = tag.find('p', class_="conditions-trails-content-others-metric-name").get_text()
        metric_value = tag.find('p', class_="conditions-trails-content-others-metric-value").get_text()

        if metric_name == 'Open Lifts':
            # if this tag is the Open Lifts metric name, the value after it is the number of lifts open
            lifts_open = metric_value
        elif metric_name == 'Open Trails':
            trails_open = metric_value

    return format_conditions_json(new_snow_inches, wind_speed, lifts_open, trails_open)


# Read Raw HTML from Copper Mountain to get snow report
def read_copper_conditions(raw_html):
    conditions_soup = BeautifulSoup(raw_html, 'html.parser')

    new_snow_inches = -1

    wind_speed = -1

    lifts_open = -1

    trail_open = -1

    return format_conditions_json(new_snow_inches, wind_speed, lifts_open, trail_open)


# Read Raw HTML from Eldora Mountain to get snow report
# Open Trails in format: <strong>Open Trails</strong></span>
# <br />Hornblower<br />Windmill<br />International<br />La Belle<br />Hot Dog Alley<br />Chute<br />Bunnyfair<br />Ryder's<br /><br />
# </li>
# Open Lifts in format: <strong>Open Lifts</strong></span><br>Alpenglow<br>Race<br>EZ<br><br></li>
# AKA for both I should find the open trails list indicator, then get the following items in <br> and count
# Find Wind Speed: 22 to 32 miles per hour --> search for re w/ miles per hour and digits beforehand

def read_eldora_conditions(raw_html):
    conditions_soup = BeautifulSoup(raw_html, 'html.parser')

    # Search for wind and snow
    wind_speed = -1
    new_snow_inches = 0

    wind_match_found = False
    snow_match_found = False

    span_tags = conditions_soup.find_all('span')
    for s_tag in span_tags:
        if wind_match_found and snow_match_found:
            break

        s_text = s_tag.text
        wind_match = re.search(r'(\d+) miles per hour', s_text)
        # Should match the first instance of inch and/or inches in the snow report (if present)
        snow_match = re.search(r'(\d+) inch', s_text)

        if wind_match:
            wind_speed = wind_match[1]
            wind_match_found = True
        if snow_match:
            new_snow_inches = snow_match[1]
            snow_match_found = True

    # Find Open lifts and Trails
    list_tags = conditions_soup.find_all('li')

    lifts_open = -1
    trails_open = -1

    open_trails_found = False
    open_lifts_found = False

    for l_tag in list_tags:
        if open_lifts_found and open_trails_found:
            break
        if l_tag.find_all('span'):
            span_tag = l_tag.find_all('span')[0]
        else:
            continue

        if span_tag.text == 'Open Trails':
            # The number of br tags is equivalent to the # of open trails + 2 based on list format w/headers and empty line
            br_tags = l_tag.find_all('br')
            trails_open = len(br_tags) - 2
            open_trails_found = True
        elif span_tag.text == 'Open Lifts':
            # # of br tags = # of open lifts + 2 based on list format w/headers and empty line
            br_tags = l_tag.find_all('br')
            lifts_open = len(br_tags) - 2
            open_lifts_found = True

    return format_conditions_json(new_snow_inches, wind_speed, lifts_open, trails_open)


# Read Raw HTML from Copper Mountain to get snow report
def read_steamboat_conditions(raw_html):
    conditions_soup = BeautifulSoup(raw_html, 'html.parser')
    return conditions_soup.prettify()

    new_snow_inches = -1

    wind_speed = -1

    lifts_open = -1

    trail_open = -1

    return format_conditions_json(new_snow_inches, wind_speed, lifts_open, trail_open)

def main():
    print("Fetching Winter Park Conditions")
    wp_conditions = scrape_resort_conditions_page(WINTER_PARK)
    print(wp_conditions)

    print("Fetching Copper Conditions")
    copper_conditions = scrape_resort_conditions_page(COPPER)
    print(copper_conditions)

    print("Fetching Eldora Conditions")
    eldora_conditions = scrape_resort_conditions_page(ELDORA)
    print(eldora_conditions)

    print("Fetching Steamboat Conditions")
    steamboat_conditions = scrape_resort_conditions_page(STEAMBOAT)
    print(steamboat_conditions)

if __name__ == "__main__":
    main()