apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: fakedir/sentiment-worker:v1
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-master
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-slave
        - name: RABBITMQ_HOST
          value: rabbitmq
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        # ports:
        # - containerPort: 5672